---
name: jmx4perl
version: 0.70_6
author:
  - Roland Huss (roland@cpan.org)
abstract: Easy JMX access to Java JEE applications
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  Module::Build: 0.34
  Test: 0
  Test::Deep: 0
  Test::More: 0
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  JSON: 2.12
  LWP::UserAgent: 0
  Module::Find: 0
  Pod::Usage: 0
  Scalar::Util: 0
  URI: 1.35
recommends:
  Config::General: 0
  Nagios::Plugin: 0.27
  Term::Clui: 0
  Term::ShellUI: 0
  Term::Size: 0.207
  Text::ParseWords: 0
configure_requires:
  Module::Build: 0.34
provides:
  JMX::Jmx4Perl:
    file: lib/JMX/Jmx4Perl.pm
    version: 0.70_6
  JMX::Jmx4Perl::Agent:
    file: lib/JMX/Jmx4Perl/Agent.pm
    version: 0
  JMX::Jmx4Perl::Agent::UserAgent:
    file: lib/JMX/Jmx4Perl/Agent/UserAgent.pm
  JMX::Jmx4Perl::Alias:
    file: lib/JMX/Jmx4Perl/Alias.pm
  JMX::Jmx4Perl::Alias::Object:
    file: lib/JMX/Jmx4Perl/Alias/Object.pm
  JMX::Jmx4Perl::Config:
    file: lib/JMX/Jmx4Perl/Config.pm
  JMX::Jmx4Perl::J4psh:
    file: lib/JMX/Jmx4Perl/J4psh.pm
  JMX::Jmx4Perl::J4psh::Command:
    file: lib/JMX/Jmx4Perl/J4psh/Command.pm
  JMX::Jmx4Perl::J4psh::Command::Global:
    file: lib/JMX/Jmx4Perl/J4psh/Command/Global.pm
  JMX::Jmx4Perl::J4psh::Command::MBean:
    file: lib/JMX/Jmx4Perl/J4psh/Command/MBean.pm
  JMX::Jmx4Perl::J4psh::Command::Server:
    file: lib/JMX/Jmx4Perl/J4psh/Command/Server.pm
  JMX::Jmx4Perl::J4psh::CommandHandler:
    file: lib/JMX/Jmx4Perl/J4psh/CommandHandler.pm
  JMX::Jmx4Perl::J4psh::CompletionHandler:
    file: lib/JMX/Jmx4Perl/J4psh/CompletionHandler.pm
  JMX::Jmx4Perl::J4psh::ServerHandler:
    file: lib/JMX/Jmx4Perl/J4psh/ServerHandler.pm
  JMX::Jmx4Perl::J4psh::Shell:
    file: lib/JMX/Jmx4Perl/J4psh/Shell.pm
  JMX::Jmx4Perl::Nagios::CheckJmx4Perl:
    file: lib/JMX/Jmx4Perl/Nagios/CheckJmx4Perl.pm
  JMX::Jmx4Perl::Nagios::SingleCheck:
    file: lib/JMX/Jmx4Perl/Nagios/SingleCheck.pm
  JMX::Jmx4Perl::Product::ActiveMQ:
    file: lib/JMX/Jmx4Perl/Product/ActiveMQ.pm
  JMX::Jmx4Perl::Product::BaseHandler:
    file: lib/JMX/Jmx4Perl/Product/BaseHandler.pm
  JMX::Jmx4Perl::Product::Geronimo:
    file: lib/JMX/Jmx4Perl/Product/Geronimo.pm
  JMX::Jmx4Perl::Product::Glassfish:
    file: lib/JMX/Jmx4Perl/Product/Glassfish.pm
  JMX::Jmx4Perl::Product::Hadoop:
    file: lib/JMX/Jmx4Perl/Product/Hadoop.pm
  JMX::Jmx4Perl::Product::JBoss:
    file: lib/JMX/Jmx4Perl/Product/JBoss.pm
  JMX::Jmx4Perl::Product::Jetty:
    file: lib/JMX/Jmx4Perl/Product/Jetty.pm
  JMX::Jmx4Perl::Product::Jonas:
    file: lib/JMX/Jmx4Perl/Product/Jonas.pm
  JMX::Jmx4Perl::Product::Resin:
    file: lib/JMX/Jmx4Perl/Product/Resin.pm
  JMX::Jmx4Perl::Product::SpringDM:
    file: lib/JMX/Jmx4Perl/Product/SpringDM.pm
  JMX::Jmx4Perl::Product::Terracotta:
    file: lib/JMX/Jmx4Perl/Product/Terracotta.pm
  JMX::Jmx4Perl::Product::Tomcat:
    file: lib/JMX/Jmx4Perl/Product/Tomcat.pm
  JMX::Jmx4Perl::Product::Unknown:
    file: lib/JMX/Jmx4Perl/Product/Unknown.pm
  JMX::Jmx4Perl::Product::Weblogic:
    file: lib/JMX/Jmx4Perl/Product/Weblogic.pm
  JMX::Jmx4Perl::Product::Websphere:
    file: lib/JMX/Jmx4Perl/Product/Websphere.pm
  JMX::Jmx4Perl::Request:
    file: lib/JMX/Jmx4Perl/Request.pm
  JMX::Jmx4Perl::Response:
    file: lib/JMX/Jmx4Perl/Response.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
